version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - cd ./spring-hw-1
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./spring-hw-1/target/spring-hw-1-1.0-SNAPSHOT.jar
    - ./spring-hw-1/Dockerfile